# Generated by Django 5.2.4 on 2025-10-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='faculty_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
