# Generated by Django 5.2.4 on 2025-09-24 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('off_day', models.CharField(max_length=15)),
                ('partitions', models.CharField(help_text='Comma-separated partition codes (e.g., A,B)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('lectures', models.IntegerField(default=0)),
                ('labs', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_time', models.DateTimeField(auto_now_add=True)),
                ('solution_found', models.BooleanField(default=False)),
                ('timetable_json', models.JSONField(blank=True, null=True)),
                ('runtime_seconds', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_app.division')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_app.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_app.subject')),
            ],
            options={
                'verbose_name_plural': 'Faculty Assignments',
                'unique_together': {('subject', 'division')},
            },
        ),
    ]
