# Generated by Django 5.2.4 on 2025-10-01 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0002_subject_double_periods'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('slot_index', models.PositiveIntegerField(help_text='The index of the period (e.g., 0 for the first period, 1 for the second)')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailability_slots', to='timetable_app.faculty')),
            ],
            options={
                'verbose_name_plural': 'Faculty Availabilities',
                'unique_together': {('faculty', 'day', 'slot_index')},
            },
        ),
    ]
