# Generated by Django 5.2.4 on 2025-10-10 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0004_semester_division_name_division_semester_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facultyavailability',
            unique_together={('faculty', 'day')},
        ),
        migrations.AddField(
            model_name='facultyavailability',
            name='slot_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facultyavailability',
            name='slot_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facultyavailability',
            name='slot_3',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facultyavailability',
            name='slot_4',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facultyavailability',
            name='slot_5',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facultyavailability',
            name='slot_6',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='facultyavailability',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='facultyavailability',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_schedule', to='timetable_app.faculty'),
        ),
        migrations.RemoveField(
            model_name='facultyavailability',
            name='slot_index',
        ),
    ]
