# Generated by Django 5.2.4 on 2025-10-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0006_division_user_faculty_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='division',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='timetableresult',
            name='user',
        ),
        migrations.AlterField(
            model_name='division',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.PositiveSmallIntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, '3rd Semester'), (4, '4th Semester'), (5, '5th Semester'), (6, '6th Semester'), (7, '7th Semester'), (8, '8th Semester')], help_text='Select the semester number', unique=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='division',
            name='user',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='user',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='user',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='user',
        ),
    ]
