# Generated by Django 5.2.4 on 2025-09-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='double_periods',
            field=models.IntegerField(default=0),
        ),
    ]
